### ISSUE TITLE
add fix-animated to use-views

### ISSUE THREAD

**Issue by tombrewsviews** [viewstools/morph#108]
run yarn add animated

then add this to src/fix-animated.js
`import Animated from 'animated/lib/targets/react-dom'

Animated.a = Animated.createAnimatedComponent('a')
Animated.button = Animated.createAnimatedComponent('button')
Animated.span = Animated.createAnimatedComponent('span')
Animated.svg = Animated.createAnimatedComponent('svg')`

and then add this line at the top (before anything else) of the file src/index.js:
import './fix-animated.js'

**Comment by dariocravero** [comment]
we'll probably drop this if we go for react-spring as proposed in #11, adding comment for reference
