### ISSUE TITLE
Nested lists/ grids

### ISSUE THREAD

**Issue by amymc** [viewstools/morph#151]
Similar to what we talked about a while back, on my own project I've implemented it like this...
 
If you specify a `pass` prop then the morpher doesn't deconstruct the contents and the inner array is available as the value specified for the `pass` property. If no `pass` property is specified it deconstructs as normal.

So, for example, my views are like this:
#### Board.view
```
from <grid
pass column
BoardColumn
```

#### BoardColumn.view
```
from <column
Cell
```

I can open a PR with that approach if you're into it. Or if you'd prefer me to do it another way let me know.

**Comment by dariocravero** [comment]
Can you give us a bit more context around the view and the output of that code? :)

**Comment by amymc** [comment]
Sorry, Yes!

##### Board.view
```
Board List
flexDirection row
from <grid
pass column
BoardColumn
```

##### BoardColumn.view
```
BoardColumn List
width 28
from <column
Cell
```

##### Board.view.js
```
const Board = props => {
  return (
    <div
      data-test-id={`${props['data-test-id'] || 'Board'}|`}
      pass="column"
      className={`views-block ${Board1}`}
    >
      {Array.isArray(props.grid) &&
        props.grid.map((column, index) => (
          <BoardColumn
            index={index}
            column={column}
            key={index}
            data-test-id={`Board.BoardColumn|`}
            className="views-block"
          />
        ))}
      {props.children}
    </div>
  );
};
```
##### BoardColumn.view.js
```
const BoardColumn = props => {
  return (
    <div
      data-test-id={`${props['data-test-id'] || 'BoardColumn'}|`}
      pass="item"
      className={`views-block ${BoardColumn1}`}
    >
      {Array.isArray(props.column) &&
        props.column.map((item, index) => (
          <Cell
            index={index}
            {...item}
            key={index}
            data-test-id={`BoardColumn.Cell|`}
            className="views-block"
          />
        ))}
      {props.children}
    </div>
  );
};
```

The data is a nested array with objects inside.

You can see what I'm doing [here](https://github.com/viewstools/morph/compare/optional-list-destructuring)
