### ISSUE TITLE
Masking input in Captures

### ISSUE THREAD

**Issue by dariocravero** [viewstools/morph#157]
Some apps need to have their inputs masked. We'd like to support that in Views.

There's some preliminary work done as a React hook [useMaskedInput](https://github.com/viewstools/use-masked-input) that we can leverage for this work.

The goal would be to do something like:

```
Capture
mask phone
```

@tombrewsviews had some ideas as to supporting some formats for known formats eg `mask phone` that would internally get expanded to what it needs to be. @tombrewsviews could you comment in here with what those would be?

However, the base mechanism would be to support any type of mask. I don’t know how we’d go about that, maybe storing the actual array in a somewhat serialised format, eg:
```
Capture
mask ["0-9", /\d/]`
```
What do you think @amymc @tombrewsviews? Tools will provide a widget to allow users to make custom masks or to choose one of the predefined types.

We will want to cast `number` and `email` types to `text` because [the library doesn't support them](https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#known-issues). It probably doesn't matter much because the masking defines the input anyway.

Then there’s also React Native support, which we’d need to see how it works because the library is targeted towards the web, so it may need a few tweaks, or we may need to use some lower level constructs for it to work, but that can happen at a later stage. For now we can ignore masking on RN.

TODO:
- [ ] Come up with known formats.
- [ ] Make base implementation of `mask` slot.
- [ ] Support known formats in `mask` slot and expand them accordingly.
- [ ] Cast `number` and `email` to `text` type when using mask.
- [ ] Support extra mask configuration. [See "possible configuration values" here](https://github.com/viewstools/use-masked-input).
- [ ] Support (if not too much work in base library) or skip React Native support.

**Comment by amymc** [comment]
I guess if a `Capture` has a `mask` then it won’t need a `type` because we can infer that, but if it doesn’t have a `mask` it would still need a `type`. Correct?

**Comment by dariocravero** [comment]
Mmm not sure, because a type also gives us a keyboard, which is more important on mobile. So ideally we'd keep it. It's a pity number doesn't work.

**Comment by amymc** [comment]
Just to clarify what I was asking is do we want this..
```
Capture
type phone
mask phone
```

or just this?
```
Capture
mask phone
```

I would keep the `type` on the morphed output regardless.

I guess the question is would a given `mask` always be of the same `type`?
Like, might someone want this instead...
```
Capture
type number
mask phone
```

**Comment by dariocravero** [comment]
Aah I see, well, since the mask will indicate a format, I’d keep the two. @tombrewsviews any thoughts?

**Comment by tombrewsviews** [comment]
I see your point Amy. You are onto something.
What about requiring one or the other?
so
Capture
mask phoneUS

and

Capture
type phone

and

Capture
type phone
maske phoneUS

would all work

**Comment by amymc** [comment]
What formats do we want to support apart from US phone numbers? @tombrewsviews

**Comment by tombrewsviews** [comment]
Good question.
I think in general most, if not all, of the ones defined here
https://nosir.github.io/cleave.js/

It would be great if we, views users, could define their own formats as well

**Comment by dariocravero** [comment]
People defining their own formats is there already @tombrewsviews. We'll need to map out the regexes from whatever cleave supports to what text-mask needs - which might be on these files https://github.com/nosir/cleave.js/blob/master/src/shortcuts.
Maybe for now we start with the custom format then?

**Comment by dariocravero** [comment]
Here's a handy post for getting a numeric keyboard when the input type isn't number https://www.filamentgroup.com/lab/type-number.html
