### ISSUE TITLE
Cannot apply data value to z-index property

### ISSUE THREAD

**Issue by alex-vladut** [viewstools/morph#205]
The following approach doesn't work with the `zIndex` property on a block:

```
SomeView View
is together
data context.index
  Horizontal
  zIndex <value
  ...
```

The generated `view.js` in this case will look something like this:

```
let styles = {}
styles.Vertical = css({ zIndex: 'var(--zIndex)' })

....

export default function SomeView({value}) {
    let data = fromData.useData({ 
      viewPath, 
      path: 'phone_number_item.indexReverse', 
      context: 'phone_number_item',
})
  return (<div style={{'--zIndex': value}}> ...
```

so it seems that in this case it is expecting the `value` to be passed through the props instead of it coming from the `data` (which is not even used).

**Comment by dariocravero** [comment]
@alex-vladut I think this https://github.com/viewstools/morph/commit/44e6fb129a2e7bfbcf0fc0e5f92e99309e6cf331 fixes it, can you check it out?

**Comment by alex-vladut** [comment]
It works now. Thanks for the fix 👍
