### ISSUE TITLE
Add helpers for the lists

### ISSUE THREAD

**Issue by tombrewsviews** [viewstools/morph#21]
The objective of this is to try avoid using .length on lists
isLast - value
isFirst - value
isEmpty - function that takes prop
getFirst - function that takes prop list
getLast - function that takes prop list
getNth - function that takes nth prop and list

optional outside of the scope of lists
isTrue - function that takes prop
isFalse - function that takes prop

**Comment by dariocravero** [comment]
`next` - next index or 0
`prev` - prev index or list.length -1

**Comment by dariocravero** [comment]
Lists will change with stories and data, so I'll be closing this for now
