### ISSUE TITLE
Allow for multiple targets to be compiled at the same time

### ISSUE THREAD

**Issue by dariocravero** [viewstools/morph#31]
Today we always compile `A.view` to `A.view.js`. However, [if you want to run your code simultaneously across web and native](https://github.com/viewsdx/yarn-workspaces-cra-crna), you need to stop the project and re-run the morpher, which isn't ideal.

Also, because of how create react app is designed, we can't leverage the platform specific file extensions `.web.js` and `.native.js` because if you `import './A.view'` it treats it as a static file.

The proposal is to output `.A.js` when only one target is specified and `.A.web.js` and `.A.native.js` when multiple are. The `.` before the name has the side effect of hiding the file in most file explorers. We can then target them in `.gitignore` like `.*.js` I think.

This change would be internal to the morpher and shouldn't affect consumers of it.

**Comment by alanmarcell** [comment]
Totally miss that. Waiting anxiously.

**Comment by dariocravero** [comment]
Hey @alanmarcell, yeah, it should be a handy feature if you're working in native and web at the same time. Just in case it's not clear from the issue's description, Views already compiles to either native or web but it just does it separately, as in, you can only run the morpher once per target at a time. Have you used Views already? :)
