### ISSUE TITLE
Morph file when duplicate has been deleted

### ISSUE THREAD

**Issue by amymc** [viewstools/morph#36]
If you create a new file with the same name as an already existing component, the morpher won't morph the new file and you'll get an error message explaining why. 

This is fine, but if you then delete the original file the morpher still won't morph the new file. In order for the morpher to morph the new file, you have to rename the file to something else and then change it back to the name you originally intended. 

Bit of an edge case I suppose but ideally as soon as you delete the original file, the new one should be morphed.

**Comment by dariocravero** [comment]
We now support multiple views with the same name, so this isn't an issue anymore :)
