### ISSUE TITLE
Disable propriety in Inputs

### ISSUE THREAD

**Issue by callogerasl** [viewstools/morph#40]
I need to use disable=false in a CaptureTextArea, but even though it's false the CaptureTextArea is still unable. 

Example:
.view Code

```
FeedbackText CaptureTextArea
autoFocus true
flex 1  
padding 8  
disabled false
when props.isSent  
disabled true 
```

Morph should translate it as:
```
<FeedbackText
  data-test-id="Feedback.FeedbackText"  
  disabled={props.isSent? true : null}
  props={props}
  className="views-block"
/>
```

**Comment by amymc** [comment]
This seems to be working for me. 

Using the `FeedbackText` view above, I get this compiled code:

```
 <textarea
        onChange={event => this.setState({ feedbackText: event.target.value })}
        value={state.feedbackText}
        data-test-id={props['data-test-id'] || 'FeedbackText'}
        autoFocus={true}
        disabled={props.isSent ? true : false}
        className={`views-block ${FeedbackText_h1kvv2k8}`}
      />
```

@dariocravero

**Comment by dariocravero** [comment]
Actually, you're right @amymc. `false` disables the textarea. Thanks for chiming in :). I wonder what was it that we saw with @callogerasl that wasn't cutting it. Let's have a look at the app tomorrow again and see if we were missing something else.
