### ISSUE TITLE
Differences between Views Tools and actual app in React Native projects

### ISSUE THREAD

**Issue by tombrewsviews** [viewstools/morph#47]
- [ ] More `flex 1` is required on the wrappers 
- [ ] `lineHeight` and `letterSpacing` are not working
- [ ] Morph textOverflow ellipsis in RN to ellipsizemode tail
- [ ] Support focus style on Captures in React Native

**Comment by dan-mckay** [comment]
Normalising text.
Wrapping lines:
```
overflow: hidden;
    text-overflow: ellipsis;
    white-space: pre-wrap;
    display: inline;
    flex: 1;
    line-height: 1.25;
```
<img width="404" alt="screen shot 2018-01-31 at 11 14 08" src="https://user-images.githubusercontent.com/1457201/35620089-e993f73c-0677-11e8-9c96-1bb53c90baed.png">


No wrapping lines (cut) same as before but:
```
    white-space: nowrap;
```

<img width="419" alt="screen shot 2018-01-31 at 11 14 43" src="https://user-images.githubusercontent.com/1457201/35620102-f419a1a2-0677-11e8-910f-ff207222b4a7.png">


If you have a container and you want to align the text inside of it (like the examples above) you'd use `alignItems flex-start` on the horizontal and then use the same line height on both texts.

cc @dariocravero

**Comment by dariocravero** [comment]
I think we could leverage https://github.com/vincentriemer/react-native-dom to render native versions when it's there
