### ISSUE TITLE
The props in FakeProps shouldn't be linted

### ISSUE THREAD

**Issue by amymc** [viewstools/morph#51]
It shouldn't matter if my fake props are not valid props but I'm seeing these errors:

<img width="434" alt="screen shot 2018-02-01 at 11 29 48" src="https://user-images.githubusercontent.com/1708243/35678192-55dbd3d8-074a-11e8-81b3-c2bdb5d4cbca.png">

For this view
```
FakeProps
from list 5
marginTop 10
when Empty
from list 0
```

**Comment by dariocravero** [comment]
FakeProps are gone! 🎉
