### ISSUE TITLE
Assume `inherit` as default value if none supplied

### ISSUE THREAD

**Issue by amymc** [viewstools/morph#66]
If no default value is supplied for a slot, the morpher should assume `inherit` for properties that can take inherit, e.g. `width`, `height`, `color` (are there more?)

So, for example, instead of requiring that default values are supplied, this would now be valid:
```
App Vertical
width <
color <
```
and then the compiled code would capture this like so:
```
App.defaultProps = {
  width: 'inherit',
  height: 'inherit',
};
```

**Comment by dariocravero** [comment]
Thought about it a bit more and I think we should still enforce those defaults there to be whatever they have to, like `100%` if you want that wherever it runs. What do you think?

**Comment by tomatuxtemple** [comment]
1. Should we also give you warning in the terminal that a slot is missing a default value? 
2. I wonder what would it inherit from?

**Comment by dariocravero** [comment]
After thinking about this for a bit, we won't go down this path because the last thing we want is inheritance :). We should probably remove the need for a default on some of those props.
