### ISSUE TITLE
when <hover should apply to custom blocks

### ISSUE THREAD

**Issue by tombrewsviews** [viewstools/morph#69]
at the moment it applies only to the basic blocks
This should be possible, granted fill is a slot in the PlayIcon view
```PlayIcon
fill white
when <hover
fill red```

here's the place when that could be fixed
https://github.com/viewstools/morph/blob/master/morph/react-dom/block-name.js#L13-L46

**Comment by dariocravero** [comment]
I thought a bit more about this and it wouldn't work with the current approach. Unless we link the elements more explicitly across views, we'd need to bind hover mouse events to the element and use state internally to handle the hover prop in that case.
The alternative for now is to include the icon at point of use or to do the mouse event handling in a logic file.
