### ISSUE TITLE
Morpher doesn't handle `flexGrow`

### ISSUE THREAD

**Issue by amymc** [viewstools/morph#73]
Linter throws an error.

<img width="539" alt="screen shot 2018-03-12 at 15 40 32" src="https://user-images.githubusercontent.com/1708243/37294968-ef77ad86-260e-11e8-9131-201d5cf806b9.png">

The compiled js has `FlexGrow` as an attribute on the element instead of in the css.

<img width="495" alt="screen shot 2018-03-12 at 16 04 51" src="https://user-images.githubusercontent.com/1708243/37295195-740e293a-260f-11e8-9458-df74c43e0395.png">

**Comment by dariocravero** [comment]
Fixed in v13 :)
