### ISSUE TITLE
Internationalisation number formatting

### ISSUE THREAD

**Issue by amymc** [viewstools/morph#74]
## Currency 
```
RegularPrice Text
text <regularPrice 100
format currency USD
when <eu
format currency EUR
```
```
const USMsg = new IntlMessageFormat(
  "{price, number, USD}",
  "en-US",
  {
    number: {
      USD: {
        style: "currency",
        currency: "USD"
      }
    }
  }
);

const EUMsg = new IntlMessageFormat(
  "{price, number, EUR}",
  "en-EUR",
  {
    number: {
      EUR: {
        style: "currency",
        currency: "EUR"
      }
    }
  }
);


export default props => {
  return (
    <h1>
      {props.isEU
        ? EUMsg.format({ price: 100 })
        : USMsg.format({ price: 100 })}
    </h1>
  );
};
```
[Sandbox](https://stackblitz.com/edit/react-bwluia?file=Currency.js)

## Percentage
```
NewPercentage Text
text 80.5
format percentage
when <es
format percentage es
```

```
const USMsg = new IntlMessageFormat(
  `{percentage, number, USPercent}`,
  "en-US",
  {
    number: {
      USPercent: {
        style: "percent",
        //prevents rounding to the nearest number
        maximumFractionDigits: 2
      }
    }
  }
);

const ESMsg = new IntlMessageFormat(
  `{percentage, number, ESPercent}`,
  "es-ES",
  {
    number: {
      ESPercent: {
        style: "percent",
        //prevents rounding to the nearest number
        maximumFractionDigits: 2
      }
    }
  }
);

export default props => {
  return (
    <h1>
       {props.isES
        ? ESMsg.format({ percentage: 0.805 })
        : USMsg.format({ percentage: 0.805 })}
    </h1>
  );
};
```
[Sandbox](https://stackblitz.com/edit/react-bwluia?file=Percentage.js)

## Date
8th July
```
FirstDate Text
text 2005-07-08 
format date medium
when <mx
format date short
```

```
const USMediumDate = new IntlMessageFormat(
  `{startDate, date, medium}`,
  "en-US"
);

const MXShortDate = new IntlMessageFormat(
  "{startDate, date, short}",
  "es-MX"
);

export default props => {
  return (
    <div>
      <h1>
        {props.isMX
          ?  MXShortDate.format({
              startDate: Date.parse("2005-07-08")
            })
          : USMediumDate.format({
              startDate: Date.parse("2005-07-08")
            })}
      </h1>
    </div>
  );
};
```

Date can also be entered in American format, so this would still be the 8th of July
```
SecondDate Text
text 07-08-2005
format date long
when <mx
format date full
```

```
const USLongDate = new IntlMessageFormat(
  `{startDate, date, long}`,
  "en-US"
);

const MXFullDate = new IntlMessageFormat(
  "{startDate, date, full}",
  "es-MX"
);

export default props => {
  return (
    <div>
      <h1>
        {props.isMX
          ? MXFullDate.format({
              startDate: Date.parse("07-08-2005")
            })
          : USLongDate.format({
              startDate: Date.parse("07-08-2005")
            })}
      </h1>
    </div>
  );
};
```
The options are `short`, `medium`, `long` and `full`

[Sandbox](https://stackblitz.com/edit/react-bwluia?file=Date.js)

## Time
```
HammerTime Text
text 3:25
format time medium
when <mx
format time short
```

```
const USMediumTime = new IntlMessageFormat(
  "{startTime, time, medium}",
  "en-US"
);

const MXShortTime = new IntlMessageFormat(
  "{startTime, time, short}",
  "es-MX"
);

export default props => {
  return (
    <div>
      <h1>
        {props.isMX
          ? MXShortTime.format({
              startTime: Date.UTC(2018, 14, 3, 3, 25)
            })
          : USMediumTime.format({
              startTime: Date.UTC(2018, 14, 3, 3, 25)
            })}
      </h1>
    </div>
  );
};
```

The options are `short`, `medium` and `long`. (`full` also exists but it is identical to `long`). 
Long includes timezone which is GMT by default.

To support 24 hour clock and other timezones we could define custom formats.

```
HammerTime Text
text 3:25
format time 24h America/New_York
when <mx
format time short 12h
```

```
const NYTime = new IntlMessageFormat(
  `{startTime, time, NYTime}`,
  "en-US",
  {
    time: {
      NYTime: {
        timeZone: "America/New_York",
        timeZoneName: "short",
        hour12: false,
        hour: "numeric",
        minute: "numeric",
        second: "numeric"
      }
    }
  }
);

const MXShortTime = new IntlMessageFormat(
  "{startTime, time, short}",
  "es-MX"
);

export default props => {
  return (
    <div>
      <h1>
        {props.isMX
          ? MXShortTime.format({
              startTime: Date.UTC(2018, 14, 3, 3, 25)
            })
          : NYTime.format({
              startTime: Date.UTC(2018, 14, 3, 3, 25)
            })}
      </h1>
    </div>
  );
};
```
But depending on where the user is we would have to parse the date received before converting to a new timezone. At the moment it assumes the date received is in UTC timezone. Maybe timezone support would be a future iteration?

For the 24h clock, alternatively we could compile the following view
```
text 3:25
format time 24h 
when <mx
format time short 12h
```
like this..
```
const USMediumTime24H = new IntlMessageFormat(
  "{startTime, time, medium}",
  "es-MX"
);

const MXShortTime12H = new IntlMessageFormat(
  "{startTime, time, short}",
  "en-US"
);

export default props => {
  return (
    <div>
      <h1>
        {props.isMX
          ? MXShortTime12H.format({
              startTime: Date.UTC(2018, 14, 3, 15, 25)
            })
          : USMediumTime24H.format({
              startTime: Date.UTC(2018, 14, 3, 15, 25)
            })}
      </h1>
    </div>
  );
};
```
So we would conver the time to the 24h clock and then in the format we would have to set it to a region that uses the 24H clock, so in `USMediumTime24H`, we would use `es-MX` to ensure it renders as `15.25`, if we use `en-US` it would render as `3.25`.

[Sandbox](https://stackblitz.com/edit/react-bwluia?file=Time.js)

**Comment by dariocravero** [comment]
Good work @amymc!

Adding this code dump after our call on it:
```
import { Subscribe } from 'unstated';
import LocalContainer from '../LocalContainer.js';
import React from 'react';

const formatters = {
  en: new Intl.NumberFormat('en-EN', { style: 'currency', currency: 'USD' }),
  es: new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'USD' }),
};

export default props => (
  <Subscribe to={[LocalContainer]}>
    {local => new Intl.NumberFormat('en-EN', { style: 'currency', currency: props.currency }).format(props.value)}
  </Subscribe>
);

export default props => (
  <Subscribe to={[LocalContainer]}>
    {local => formatters[local.lang].format(props.value)}
  </Subscribe>
);


// Text
// color red
// text <price
// format currency USD

<span>
  {props.price}
</span>
  
<span>
  <FormatCurrency value={price} currency='USD' />
</span>
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by amymc** [comment]
@dariocravero Updated the sandbox with the approach above. Completely removed `format.js`, just using `Intl.NumberFormat` and `Intl.DateTimeFormat` directly. It's looking a lot more concise :grinning:. 

https://stackblitz.com/edit/react-bwluia

From what I can see the advantages of using `format.js` are things that  aren't relevant to us, i.e. compatibility all the way down to IE6, integrations with React, Ember etc.

Re dates:  Year, month and day can be either `numeric` or `2-digit`. Rather than letting the user set the format individually for all three of those, how about we just allow them to either have them all `numeric` or all `2-digit`. Then we can keep the view terse so rather than having something like this:
```
FirstDate Text
text 2005-07-08
format date numeric weekday long year numeric month numeric day 2-digit
```

We could just have this
```
FirstDate Text
text 2005-07-08
format date numeric weekday long
```

For reference, all available options for `Intl.DateTimeFormat` are [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Syntax)

**Comment by dariocravero** [comment]
Yeah, you're right, because Views disappears when we go to the client, it makes sense to produce the best code possible for that scenario.

Regarding the options, I think it's best if we keep it explicit despite it being a bit longer, it's easier to know what's going on. I wonder what @tomatuxtemple things about that?

Also, how're the parameters parsed/applied? Ie, in the first example: `date numeric weekday long year numeric month numeric day 2-digit`, it seems to be `value key` like `numeric weekday` apart from the last bit of it `day 2-digit`. I have a feeling going about it like `key value` like `day 2-digit` might be a bit more intuitive and it would follow the pattern we use in animations too.

What do you think?

**Comment by amymc** [comment]
Sorry that was a typo 😬, there was a stray numeric in there!

so it should be this..
```
format date weekday long year numeric month numeric day 2-digit
```
The options for `weekday` are different from the others. So for weekday we can have `narrow`, `short`, `long`.

**Comment by dariocravero** [comment]
nice :)
