### ISSUE TITLE
I18n support

### ISSUE THREAD

**Issue by dariocravero** [viewstools/morph#75]
- [x] understanding i18n scopes and implementing local context WIP @dariocravero
```
Text
text hi
when <es
text hola
```

- [x] formatting strings WIP @amymc #74 

- [x] languages extraction/injection tool
  - [x] extract WIP @neesonch https://github.com/viewstools/get-text/tree/with-path 
  - [x] inject WIP @eugenserbanescu https://github.com/viewstools/get-text/tree/set

- [x] text interpolation #56

**Comment by amymc** [comment]
Note to selves: When writing the docs on this, mention that `array.find()` needs a polyfill on IE (e.g. https://www.npmjs.com/package/ie-array-find-polyfill)

**Comment by dariocravero** [comment]
Now that #85 is merged, we're done with I18n! :) Next up docs... 🙈
