### ISSUE TITLE
Display:block doesn't work

### ISSUE THREAD

**Issue by amymc** [viewstools/morph#91]
If i try to set a display property on an element it gets put as property directly on the element instead of in the styles.

For example, if I have this view 
```
Title Text
display block
text Let me have a block element Dario!
```

It compiles to this
```
<span
     data-test-id={`Read.Text:4|`}
    display="block"
    className={`views-block ${Text_hb97fvs}`}
>
   Let me have a block element Dario!
</span>
```

I guess this was by design because we're living in a flex world but I want to have text-overflow ellipsis on a span element, but it won't work without `display: block`.

**Comment by dariocravero** [comment]
Thanks for spotting that :). Fixed and released as v13.0.8!
