### ISSUE TITLE
Replacing the onClick with platform agnostic interactions

### ISSUE THREAD

**Issue by tombrewsviews** [viewstools/morph#96]
now we have onClick only but we need more feedback on interactions

our thinking is to use `press` and `release` to allow for the feedback on the actions to be controlled in the views code

we would use it in `when` conditions and as a replacement for the `onClick` prop
in this new pattern we would use `onPress` and `onRelease` to call a function

**Comment by dariocravero** [comment]
```
Vertical
onPress <
onRelease <
when <press
when <release
```

**Comment by amymc** [comment]
Ok, So say we had this view
```
App Vertical
onPress <
onRelease <
backgroundColor blue
when <press
backgroundColor red
when <release
backgroundColor green
Text
text Hey
when <press
text Stay a while
when <release
text Dont go 😭
```

On DOM would that look like this? ...
```
const Vertical = styled(div)(
  ({ props }) => ({
    backgroundColor: props.isPressed ? 'red' : props.isReleased ? 'green' : 'blue',
  })
);


class App extends React.Component {
  state={
    isPressed: false,
    isReleased: false
  }

  onMouseDown = () => {
    this.setState({isPressed: true})
    this.props.onPress();
  }

  onMouseUp = () => {
    this.setState({isReleased: true})
    this.props.onRelease();
  }

  render() {
    const { props } = this;

    return (
      <Vertical
        onMouseDown={this.onMouseDown} onMouseUp={this.onMouseUp}
      >
        <Text>
          {props.isPressed ? 'Stay a while' : props.isReleased ? 'Dont go 😭' : 'Hey'}
        </Text>
      </Vertical>
    );
  }
}

```

**Comment by dariocravero** [comment]
Pretty much yeah, I guess there are a couple of things to take into consideration like:
- if you don't use `when <press` or `when <released` the state for it shouldn't be there
- `onRelease` should have a "reset" mechanism after some timeout I guess (if the component is still mounted)

We could also extract it into a pattern and do something like:
```
class PressRelease extends React.Component {
  static defaultProps = {
    resetAfter: 2500,
  }

  constructor(props) {
    super(props)

    this.state = {
      onPress: this.onPress,
      onRelease: this.onRelease,
      // the internals might be `pressed` and `released` instead of `isPressed` and `isReleased` to keep it closer to the system whens like `hover`
      pressed: false,
      released: false,
    }
  }

  componentWillUnmount() {
    this.willUnmount = true
  }

  onPress = () => {
    this.setState({ pressed: true })
  }

  onRelease = () => {
    this.setState({ pressed: false, released: true }, () => {
      setTimeout(this.reset, this.props.resetAfter)
    })
  }

  reset = () => {
    if (!this.state.pressed && !this.willUnmount) {
      this.setState({ released: false })
    }
  }

  render() {
    return this.props.children(this.state)
  }
}
```

Then we can use it like:
```
const App = props => (
  <PressRelease>
    {({ released, pressed, onPress, onRelease }) => (
      <Vertical
        props={{
          ...props,
          released,
          pressed,
        }}
        onMouseDown={compose(onPress, props.onPress)}
        onMouseUp={compose(onRelease, props.onRelease)}
      >
        <Text>
          {pressed ? 'Stay a while' : released ? 'Dont go 😭' : 'Hey'}
        </Text>
      </Vertical>
    )}
  </PressRelease>
)
```

I think the first question though is: what do you think about the proposed semantics? Do they make sense?

There's a thing that just came to mind: what happens with touch events? Do we get a conflict if we set `onMouseDown` and `onTouchStart`? Should we try to work that out based off the environment?

**Comment by dariocravero** [comment]
Another thought, is not using `onClick` problematic for keyboard accessibility?

**Comment by amymc** [comment]
That pattern looks legit. So I guess it would be up to the user to pass in a `resetAfter` prop then?

Re the semantics, well `onPress`, `onRelease` makes sense to me, but I'm not sold on `when <press`, `when <release`. Normally a `when` is a defined state, like `when <isLoggedIn` or whatever. For me at least, conceptually these are a bit different, they're short-lived, they're just true when an action is happening and then they're over. Do you think there's a need for them?

**Comment by amymc** [comment]
Re `onMouseDown` and `onTouchStart`, according to [this](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent) we can have both on an element. `onTouchStart` will be fired first.

Re keyboard accessibility, would something like this work?
```
 <Vertical
        props={{
          ...props,
          released,
          pressed,
        }}
        onMouseDown={compose(onPress, props.onPress)}
        onMouseUp={compose(onRelease, props.onRelease)}
        onKeyDown={compose(onPress, props.onPress)}
        onKeyUp={compose(onRelease, props.onRelease)}
      >
        <Text>
          {pressed ? 'Stay a while' : released ? 'Dont go 😭' : 'Hey'}
        </Text>
      </Vertical>
```

And then in the `PressRelease` component...
```
 onPress = (e) => {
    if(e.keycode && e.keycode !== 13) return
    this.setState({ pressed: true })
  }

  onRelease = (e) => {
    if(e.keycode && e.keycode !== 13) return
    this.setState({ pressed: false, released: true }, () => {
      setTimeout(this.reset, this.props.resetAfter)
    })
  }
```
